#!/bin/sh
# This is no longer used because it will block retrying to install
# dependencies if they didn't install correctly the first time,
# plus it's not as useful for saving time now that services can be
# initialized individually.

checksum='package-lock.sha512'

if ! sha512sum --check --status $checksum 2>/dev/null; then
  npm ci
  sha512sum package-lock.json > $checksum
fi
